// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// Section: imports

use super::*;
use crate::api::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::wasm_bindgen;
use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();

// Section: dart2rust

impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for String {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
        unimplemented!()
    }
}
impl CstDecode<String> for String {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> String {
        self
    }
}
impl CstDecode<Vec<Contract>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<Contract> {
        self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
            .unwrap()
            .iter()
            .map(CstDecode::cst_decode)
            .collect()
    }
}
impl CstDecode<Vec<ContractPrice>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<ContractPrice> {
        self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
            .unwrap()
            .iter()
            .map(CstDecode::cst_decode)
            .collect()
    }
}
impl CstDecode<Vec<FundingInfo>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<FundingInfo> {
        self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
            .unwrap()
            .iter()
            .map(CstDecode::cst_decode)
            .collect()
    }
}
impl CstDecode<Vec<SpotPriceInfo>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<SpotPriceInfo> {
        self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
            .unwrap()
            .iter()
            .map(CstDecode::cst_decode)
            .collect()
    }
}
impl CstDecode<Vec<u32>> for Box<[u32]> {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<u32> {
        self.into_vec()
    }
}
impl CstDecode<Vec<u8>> for Box<[u8]> {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<u8> {
        self.into_vec()
    }
}
impl CstDecode<Option<String>> for Option<String> {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Option<String> {
        self.map(CstDecode::cst_decode)
    }
}
impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
        unimplemented!()
    }
}
impl CstDecode<AutoDeleveraging> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> AutoDeleveraging {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AutoDeleveraging>,
            >,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<ChangePubKey> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> ChangePubKey {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangePubKey>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Contract> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Contract {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contract>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<ContractMatching> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> ContractMatching {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractMatching>,
            >,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<ContractPrice> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> ContractPrice {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractPrice>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<EthTxOption> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> EthTxOption {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EthTxOption>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<ForcedExit> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> ForcedExit {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ForcedExit>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Funding> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Funding {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Funding>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<FundingInfo> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> FundingInfo {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FundingInfo>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Liquidation> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Liquidation {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Liquidation>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Order> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Order {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Order>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<OrderMatching> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> OrderMatching {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OrderMatching>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Parameter> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Parameter {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Parameter>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Signer> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Signer {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Signer>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<SpotPriceInfo> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> SpotPriceInfo {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpotPriceInfo>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Transfer> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Transfer {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transfer>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<UpdateGlobalVar> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> UpdateGlobalVar {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UpdateGlobalVar>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Wallet> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Wallet {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<Withdraw> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Withdraw {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Withdraw>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<ZkLinkSignature> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> ZkLinkSignature {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSignature>>,
        >::cst_decode(
            self
        ))
    }
}
impl CstDecode<ZkLinkSigner> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> ZkLinkSigner {
        flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
            RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSigner>>,
        >::cst_decode(
            self
        ))
    }
}
impl
    CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AutoDeleveraging>>,
    > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AutoDeleveraging>>
    {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangePubKey>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangePubKey>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contract>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contract>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl
    CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractMatching>>,
    > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractMatching>>
    {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl
    CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractPrice>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractPrice>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EthTxOption>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EthTxOption>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ForcedExit>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ForcedExit>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Funding>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Funding>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FundingInfo>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FundingInfo>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Liquidation>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Liquidation>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Order>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Order>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl
    CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OrderMatching>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OrderMatching>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Parameter>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Parameter>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Signer>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Signer>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl
    CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpotPriceInfo>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpotPriceInfo>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transfer>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transfer>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl
    CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UpdateGlobalVar>>,
    > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UpdateGlobalVar>>
    {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Withdraw>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Withdraw>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl
    CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSignature>>,
    > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSignature>>
    {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSigner>>>
    for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSigner>> {
        #[cfg(target_pointer_width = "64")]
        {
            compile_error!("64-bit pointers are not supported.");
        }
        unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
    }
}
impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> String {
        self.as_string().expect("non-UTF-8 string, or not a string")
    }
}
impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self.is_truthy()
    }
}
impl CstDecode<f64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> f64 {
        self.unchecked_into_f64() as _
    }
}
impl CstDecode<i16> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i16 {
        self.unchecked_into_f64() as _
    }
}
impl CstDecode<Vec<u32>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<u32> {
        self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint32Array>()
            .to_vec()
            .into()
    }
}
impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<u8> {
        self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
            .to_vec()
            .into()
    }
}
impl CstDecode<u16> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u16 {
        self.unchecked_into_f64() as _
    }
}
impl CstDecode<u32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self.unchecked_into_f64() as _
    }
}
impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self.unchecked_into_f64() as _
    }
}
impl CstDecode<usize> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> usize {
        ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
    }
}

#[wasm_bindgen]
pub fn wire__crate__api__AutoDeleveraging_new(
    account_id: u32,
    sub_account_id: u8,
    sub_account_nonce: u32,
    contract_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    margin_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    adl_account_id: u32,
    pair_id: u16,
    adl_size: String,
    adl_price: String,
    fee: String,
    fee_token: u16,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__AutoDeleveraging_new_impl(
        account_id,
        sub_account_id,
        sub_account_nonce,
        contract_prices,
        margin_prices,
        adl_account_id,
        pair_id,
        adl_size,
        adl_price,
        fee,
        fee_token,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__AutoDeleveraging_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__AutoDeleveraging_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__AutoDeleveraging_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__AutoDeleveraging_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ChangePubKey_get_eth_sign_msg(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    nonce: u32,
    account_id: u32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ChangePubKey_get_eth_sign_msg_impl(that, nonce, account_id)
}

#[wasm_bindgen]
pub fn wire__crate__api__ChangePubKey_new(
    chain_id: u8,
    account_id: u32,
    sub_account_id: u8,
    new_pubkey_hash: String,
    fee_token: u32,
    fee: String,
    nonce: u32,
    eth_signature: Option<String>,
    ts: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ChangePubKey_new_impl(
        chain_id,
        account_id,
        sub_account_id,
        new_pubkey_hash,
        fee_token,
        fee,
        nonce,
        eth_signature,
        ts,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__ChangePubKey_set_eth_auth_data(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    sig: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ChangePubKey_set_eth_auth_data_impl(that, sig)
}

#[wasm_bindgen]
pub fn wire__crate__api__ChangePubKey_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ChangePubKey_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__ChangePubKey_to_eip712_request_payload(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    chain_id: u32,
    address: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ChangePubKey_to_eip712_request_payload_impl(that, chain_id, address)
}

#[wasm_bindgen]
pub fn wire__crate__api__ChangePubKey_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ChangePubKey_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ContractMatching_new(
    account_id: u32,
    sub_account_id: u8,
    taker: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    maker: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    fee: String,
    fee_token: u16,
    contract_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    margin_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ContractMatching_new_impl(
        account_id,
        sub_account_id,
        taker,
        maker,
        fee,
        fee_token,
        contract_prices,
        margin_prices,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__ContractMatching_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ContractMatching_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__ContractMatching_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ContractMatching_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ContractPrice_new(
    pair_id: u16,
    market_price: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ContractPrice_new_impl(pair_id, market_price)
}

#[wasm_bindgen]
pub fn wire__crate__api__Contract_new(
    account_id: u32,
    sub_account_id: u8,
    slot_id: u32,
    nonce: u32,
    pair_id: u16,
    size: String,
    price: String,
    direction: bool,
    maker_fee_rate: u8,
    taker_fee_rate: u8,
    has_subsidy: bool,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Contract_new_impl(
        account_id,
        sub_account_id,
        slot_id,
        nonce,
        pair_id,
        size,
        price,
        direction,
        maker_fee_rate,
        taker_fee_rate,
        has_subsidy,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Contract_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Contract_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__Contract_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Contract_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__EthTxOption_new(
    is_support_eip1559: bool,
    to: String,
    nonce: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    value: Option<String>,
    gas: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    gas_price: Option<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__EthTxOption_new_impl(is_support_eip1559, to, nonce, value, gas, gas_price)
}

#[wasm_bindgen]
pub fn wire__crate__api__ForcedExit_new(
    to_chain_id: u8,
    initiator_account_id: u32,
    initiator_sub_account_id: u8,
    target_sub_account_id: u8,
    target: String,
    l2_source_token: u32,
    l1_target_token: u32,
    exit_amount: String,
    initiator_nonce: u32,
    withdraw_to_l1: bool,
    ts: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ForcedExit_new_impl(
        to_chain_id,
        initiator_account_id,
        initiator_sub_account_id,
        target_sub_account_id,
        target,
        l2_source_token,
        l1_target_token,
        exit_amount,
        initiator_nonce,
        withdraw_to_l1,
        ts,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__ForcedExit_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ForcedExit_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__ForcedExit_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ForcedExit_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__FundingInfo_new(
    pair_id: u16,
    price: String,
    funding_rate: i16,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__FundingInfo_new_impl(pair_id, price, funding_rate)
}

#[wasm_bindgen]
pub fn wire__crate__api__Funding_new(
    account_id: u32,
    sub_account_id: u8,
    sub_account_nonce: u32,
    funding_account_ids: Box<[u32]>,
    fee: String,
    fee_token: u16,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Funding_new_impl(
        account_id,
        sub_account_id,
        sub_account_nonce,
        funding_account_ids,
        fee,
        fee_token,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Funding_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Funding_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__Funding_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Funding_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__Liquidation_new(
    account_id: u32,
    sub_account_id: u8,
    sub_account_nonce: u32,
    contract_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    margin_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    liquidation_account_id: u32,
    fee: String,
    fee_token: u16,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Liquidation_new_impl(
        account_id,
        sub_account_id,
        sub_account_nonce,
        contract_prices,
        margin_prices,
        liquidation_account_id,
        fee,
        fee_token,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Liquidation_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Liquidation_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__Liquidation_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Liquidation_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__OrderMatching_new(
    account_id: u32,
    sub_account_id: u8,
    taker: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    maker: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    fee: String,
    fee_token: u32,
    contract_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    margin_prices: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    expect_base_amount: String,
    expect_quote_amount: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__OrderMatching_new_impl(
        account_id,
        sub_account_id,
        taker,
        maker,
        fee,
        fee_token,
        contract_prices,
        margin_prices,
        expect_base_amount,
        expect_quote_amount,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__OrderMatching_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__OrderMatching_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__OrderMatching_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__OrderMatching_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__Order_new(
    account_id: u32,
    sub_account_id: u8,
    slot_id: u32,
    nonce: u32,
    base_token_id: u32,
    quote_token_id: u32,
    amount: String,
    price: String,
    is_sell: bool,
    maker_fee_rate: u8,
    taker_fee_rate: u8,
    has_subsidy: bool,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Order_new_impl(
        account_id,
        sub_account_id,
        slot_id,
        nonce,
        base_token_id,
        quote_token_id,
        amount,
        price,
        is_sell,
        maker_fee_rate,
        taker_fee_rate,
        has_subsidy,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Order_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Order_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__Order_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Order_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__Parameter_contract_info(
    pair_id: u16,
    symbol: String,
    initial_margin_rate: u16,
    maintenance_margin_rate: u16,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Parameter_contract_info_impl(
        pair_id,
        symbol,
        initial_margin_rate,
        maintenance_margin_rate,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Parameter_fee_account(
    account_id: u32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Parameter_fee_account_impl(account_id)
}

#[wasm_bindgen]
pub fn wire__crate__api__Parameter_funding_infos(
    infos: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Parameter_funding_infos_impl(infos)
}

#[wasm_bindgen]
pub fn wire__crate__api__Parameter_insurance_fund_account(
    account_id: u32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Parameter_insurance_fund_account_impl(account_id)
}

#[wasm_bindgen]
pub fn wire__crate__api__Parameter_margin_info(
    margin_id: u8,
    symbol: Option<String>,
    token_id: u32,
    ratio: u8,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Parameter_margin_info_impl(margin_id, symbol, token_id, ratio)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_create_signed_contract(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    contract: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_create_signed_contract_impl(that, contract)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_create_signed_order(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    order: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_create_signed_order_impl(that, order)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_eth_signer(
    eth_private_key: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_eth_signer_impl(eth_private_key)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_auto_deleveraging(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_auto_deleveraging_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_change_pubkey_with_create2data_auth(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    creator_address: String,
    salt_arg: String,
    code_hash: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_change_pubkey_with_create2data_auth_impl(
        that,
        tx,
        creator_address,
        salt_arg,
        code_hash,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_change_pubkey_with_eth_ecdsa_auth(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_change_pubkey_with_eth_ecdsa_auth_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_change_pubkey_with_onchain(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_change_pubkey_with_onchain_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_contract_matching(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_contract_matching_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_forced_exit(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_forced_exit_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_funding(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_funding_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_liquidation(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_liquidation_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_order_matching(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_order_matching_impl(that, tx)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_transfer(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    token_symbol: String,
    chain_id: Option<String>,
    addr: Option<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_transfer_impl(that, tx, token_symbol, chain_id, addr)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_sign_withdraw(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    token_symbol: String,
    chain_id: Option<String>,
    addr: Option<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_sign_withdraw_impl(that, tx, token_symbol, chain_id, addr)
}

#[wasm_bindgen]
pub fn wire__crate__api__Signer_starknet_signer(
    eth_private_key: String,
    starknet_chain_id: String,
    starknet_addr: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Signer_starknet_signer_impl(eth_private_key, starknet_chain_id, starknet_addr)
}

#[wasm_bindgen]
pub fn wire__crate__api__SpotPriceInfo_new(
    token_id: u32,
    price: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__SpotPriceInfo_new_impl(token_id, price)
}

#[wasm_bindgen]
pub fn wire__crate__api__Transfer_get_eth_sign_msg(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    token_symbol: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Transfer_get_eth_sign_msg_impl(that, token_symbol)
}

#[wasm_bindgen]
pub fn wire__crate__api__Transfer_new(
    account_id: u32,
    to_address: String,
    from_sub_account_id: u8,
    to_sub_account_id: u8,
    token: u32,
    fee: String,
    amount: String,
    nonce: u32,
    ts: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Transfer_new_impl(
        account_id,
        to_address,
        from_sub_account_id,
        to_sub_account_id,
        token,
        fee,
        amount,
        nonce,
        ts,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Transfer_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Transfer_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__Transfer_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Transfer_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__UpdateGlobalVar_new(
    from_chain_id: u8,
    sub_account_id: u8,
    parameter: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    serial_id: f64,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__UpdateGlobalVar_new_impl(from_chain_id, sub_account_id, parameter, serial_id)
}

#[wasm_bindgen]
pub fn wire__crate__api__UpdateGlobalVar_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__UpdateGlobalVar_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_approve_erc20(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    contract: String,
    amount: String,
    eth_params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) {
    wire__crate__api__Wallet_approve_erc20_impl(port_, that, contract, amount, eth_params)
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_deposit_erc20(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    sub_account_id: u8,
    deposit_to: String,
    token_addr: String,
    amount: String,
    mapping: bool,
    eth_params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    is_gateway: bool,
) {
    wire__crate__api__Wallet_deposit_erc20_impl(
        port_,
        that,
        sub_account_id,
        deposit_to,
        token_addr,
        amount,
        mapping,
        eth_params,
        is_gateway,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_deposit_eth(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    sub_account_id: u8,
    deposit_to: String,
    eth_params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    is_gateway: bool,
) {
    wire__crate__api__Wallet_deposit_eth_impl(
        port_,
        that,
        sub_account_id,
        deposit_to,
        eth_params,
        is_gateway,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_full_exit(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    account_id: u32,
    sub_account_id: u8,
    token_id: u16,
    mapping: bool,
    eth_params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) {
    wire__crate__api__Wallet_full_exit_impl(
        port_,
        that,
        account_id,
        sub_account_id,
        token_id,
        mapping,
        eth_params,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_get_balance(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) {
    wire__crate__api__Wallet_get_balance_impl(port_, that)
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_get_deposit_fee(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    eth_params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) {
    wire__crate__api__Wallet_get_deposit_fee_impl(port_, that, eth_params)
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_get_nonce(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    block_number: String,
) {
    wire__crate__api__Wallet_get_nonce_impl(port_, that, block_number)
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_new(
    url: String,
    private_key: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Wallet_new_impl(url, private_key)
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_set_auth_pubkey_hash(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    nonce: f64,
    new_pubkey_hash: String,
    eth_params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) {
    wire__crate__api__Wallet_set_auth_pubkey_hash_impl(
        port_,
        that,
        nonce,
        new_pubkey_hash,
        eth_params,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Wallet_wait_for_transaction(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    tx_hash: String,
    timeout: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) {
    wire__crate__api__Wallet_wait_for_transaction_impl(port_, that, tx_hash, timeout)
}

#[wasm_bindgen]
pub fn wire__crate__api__Withdraw_get_eth_sign_msg(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    token_symbol: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Withdraw_get_eth_sign_msg_impl(that, token_symbol)
}

#[wasm_bindgen]
pub fn wire__crate__api__Withdraw_new(
    account_id: u32,
    sub_account_id: u8,
    to_chain_id: u8,
    to_address: String,
    l2_source_token: u32,
    l1_target_token: u32,
    amount: String,
    call_data: Option<String>,
    fee: String,
    nonce: u32,
    withdraw_to_l1: bool,
    withdraw_fee_ratio: u16,
    ts: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Withdraw_new_impl(
        account_id,
        sub_account_id,
        to_chain_id,
        to_address,
        l2_source_token,
        l1_target_token,
        amount,
        call_data,
        fee,
        nonce,
        withdraw_to_l1,
        withdraw_fee_ratio,
        ts,
    )
}

#[wasm_bindgen]
pub fn wire__crate__api__Withdraw_sign(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    zk_link_signer: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Withdraw_sign_impl(that, zk_link_signer)
}

#[wasm_bindgen]
pub fn wire__crate__api__Withdraw_to_json(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__Withdraw_to_json_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSignature_get_pubkey(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSignature_get_pubkey_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSignature_get_signature(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSignature_get_signature_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSigner_eth_sig(
    sig: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSigner_eth_sig_impl(sig)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSigner_get_pubkey(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSigner_get_pubkey_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSigner_get_pubkey_hash(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSigner_get_pubkey_hash_impl(that)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSigner_sign_musig(
    that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    msg: Box<[u8]>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSigner_sign_musig_impl(that, msg)
}

#[wasm_bindgen]
pub fn wire__crate__api__ZkLinkSigner_starknet_sig(
    sig: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__ZkLinkSigner_starknet_sig_impl(sig)
}

#[wasm_bindgen]
pub fn wire__crate__api__closest_packable_fee_amount(
    fee: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__closest_packable_fee_amount_impl(fee)
}

#[wasm_bindgen]
pub fn wire__crate__api__closest_packable_token_amount(
    amount: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__closest_packable_token_amount_impl(amount)
}

#[wasm_bindgen]
pub fn wire__crate__api__init_app(port_: flutter_rust_bridge::for_generated::MessagePort) {
    wire__crate__api__init_app_impl(port_)
}

#[wasm_bindgen]
pub fn wire__crate__api__is_fee_amount_packable(
    fee: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__is_fee_amount_packable_impl(fee)
}

#[wasm_bindgen]
pub fn wire__crate__api__is_token_amount_packable(
    amount: String,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__is_token_amount_packable_impl(amount)
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAutoDeleveraging(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AutoDeleveraging>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAutoDeleveraging(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AutoDeleveraging>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangePubKey(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangePubKey>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangePubKey(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangePubKey>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContract(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contract>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContract(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contract>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContractMatching(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractMatching>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContractMatching(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractMatching>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContractPrice(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractPrice>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContractPrice(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContractPrice>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEthTxOption(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EthTxOption>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEthTxOption(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EthTxOption>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerForcedExit(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ForcedExit>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerForcedExit(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ForcedExit>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFunding(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Funding>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFunding(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Funding>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFundingInfo(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FundingInfo>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFundingInfo(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FundingInfo>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiquidation(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Liquidation>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiquidation(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Liquidation>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrder(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Order>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrder(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Order>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrderMatching(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OrderMatching>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrderMatching(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OrderMatching>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerParameter(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Parameter>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerParameter(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Parameter>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSigner(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Signer>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSigner(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Signer>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpotPriceInfo(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpotPriceInfo>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpotPriceInfo(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpotPriceInfo>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransfer(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transfer>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransfer(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transfer>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateGlobalVar(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UpdateGlobalVar>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateGlobalVar(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UpdateGlobalVar>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWithdraw(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Withdraw>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWithdraw(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Withdraw>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkLinkSignature(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSignature>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkLinkSignature(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSignature>>::decrement_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkLinkSigner(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSigner>>::increment_strong_count(ptr as _);
    }
}

#[wasm_bindgen]
pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkLinkSigner(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkLinkSigner>>::decrement_strong_count(ptr as _);
    }
}
