name: zklink
description: "zkLink Dart SDK"
homepage: "https://zk.link"

version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  flutter_rust_bridge: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^12.0.0
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
