[package]
name = "zklink_provider"
version = "0.1.0"
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = { version = "0.3.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.137"
serde_json = "1.0"
zklink_sdk_signers = { path = "../signers" }
zklink_sdk_types = { path = "../types" }
thiserror = "1.0"
wasm-bindgen = { version = "0.2.87", features = ["serde-serialize"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonrpsee = { version = "0.20.1", features = ["http-client","macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
jsonrpsee = { version = "0.20.1", features = ["macros","jsonrpsee-types","client-core"] }

[dev-dependencies]
serde_json = "1.0"
wasm-bindgen-test = "0.3"
tokio = { version = "1", features = ["full"] }

[features]
default = []
ffi = []
