[package]
name = "zklink_sdk_provider"
version = "2.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = { version = "0.3.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = "1.0.137"
thiserror = "1.0"
wasm-bindgen = { version = "0.2.87", features = ["serde-serialize"] }
zklink_sdk_signers = { path = "../signers" }
zklink_sdk_types = { path = "../types" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonrpsee = { version = "0.21", features = ["http-client","macros"] }
jsonrpsee-http-client = "0.21"
jsonrpsee-core = "0.21"

[target.'cfg(target_arch = "wasm32")'.dependencies]
jsonrpsee = { version = "0.21", features = ["macros","jsonrpsee-types","client-core"] }
getrandom = { version = "0.2.11", features = ["js"] }
uuid = "0.8"

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
wasm-bindgen-test = "0.3"

[features]
default = []
ffi = []
web =[]
